// S3-1: emit the search tables as a C header (./s3_gen h > tables.h)
// or as assembly (./s3_gen s > tables.s). Table set and layout are the
// Stage 2 design (s2_6.c); the build functions are copied from there.
#include "../stage2/common.h"

#define K 9

static uint8_t odist[729];
static uint8_t otab[729];
static uint8_t big[5040 * K];

/* ---------- copied from s2_6.c ---------- */
static void build_odist(void)
{
    memset(odist, 0xFF, sizeof odist);
    odist[0] = 0;
    for (int d = 0;; d++) {
        int found = 0;
        for (int o = 0; o < 729; o++) {
            if (odist[o] != d) continue;
            for (int face = 0; face < 3; face++) {
                int no = o;
                for (int turn = 0; turn < 3; turn++) {
                    no = omove[face][no];
                    if (odist[no] == 0xFF) {
                        odist[no] = d + 1;
                        found++;
                    }
                }
            }
        }
        if (found == 0) break;
    }
}

static void build_otab(void)
{
    for (int o = 0; o < 729; o++) {
        state_t x;
        unrank_state(o, &x);
        otab[o] = x.o[0] * 3 + x.o[1];
    }
}

static void build_big(void)
{
    memset(big, 0xFF, sizeof big);
    for (int r = 0; r < STATES; r++) {
        int p = r / 729, o = r % 729;
        int idx = p * K + otab[o];
        if (depth[r] < big[idx]) big[idx] = depth[r];
    }
}

/* ---------- emitters ---------- */
static int asm_mode;

/* One table: name, element size (1 or 2 bytes), data, count. */
static void emit(const char *name, int size, const void *data, int n)
{
    const uint8_t *b = data;
    const uint16_t *h = data;
    if (asm_mode) {
        printf("\n    .globl %s\n    .align %d\n%s:    # %d x %d B = %d B",
               name, size == 2 ? 1 : 0, name, n, size, n * size);
    } else {
        printf("\n/* %d x %d B = %d B */\nstatic const %s %s[%d] = {", n, size,
               n * size, size == 2 ? "uint16_t" : "uint8_t", name, n);
    }
    for (int i = 0; i < n; i++) {
        int v = size == 2 ? h[i] : b[i];
        if (i % 16 == 0) {
            if (asm_mode)
                printf("\n    %s %d", size == 2 ? ".half" : ".byte", v);
            else
                printf("\n    %d,", v);
        } else {
            printf(asm_mode ? ",%d" : " %d,", v);
        }
    }
    printf(asm_mode ? "\n" : "\n};\n");
}

#ifndef S3_GEN_NO_MAIN
int main(int argc, char **argv)
{
    if (argc != 2 || (argv[1][0] != 'h' && argv[1][0] != 's')) {
        fprintf(stderr, "usage: %s h|s\n", argv[0]);
        return 2;
    }
    asm_mode = argv[1][0] == 's';

    build_moves();
    build_depth();
    build_odist();
    build_otab();
    build_big();

    int total = sizeof pmove + sizeof omove + sizeof big + sizeof otab + sizeof odist;
    if (asm_mode)
        printf("# Generated by s3_gen.c -- do not edit. Total %d B.\n"
               "# Ripes rejects .section .rodata, so the tables go in .data.\n"
               "    .data\n", total);
    else
        printf("/* Generated by s3_gen.c -- do not edit. Total %d B. */\n"
               "#include <stdint.h>\n#define K %d\n", total, K);

    /* pmove/omove are [face][index]: flattened face-major. */
    emit("pmove", 2, pmove, 3 * 5040);
    emit("omove", 2, omove, 3 * 729);
    emit("big", 1, big, 5040 * K);
    emit("otab", 1, otab, 729);
    emit("odist", 1, odist, 729);
    return 0;
}
#endif
